#!/bin/bash

label="$1"
execp=

if test -z "$MA"; then
    echo "no window context" 1>&2
    exit 1
fi

if test -n "$HERE"; then
    execp=$HERE/exec/
fi

if test -z "$1"; then
    echo "usage: awd LABEL" 1>&2
    exit 1
fi

dir=`pwd`
exec ${execp}ma-eval -async $MA "UpdateTag \"$dir/-$1\""
