#!/bin/sh
#
# grep common files for patterns

if test -z "$1"; then
    echo "usage: g PATTERN [FILENAME ...]" 1>&2
    exit 1
fi

pat="$1"
shift

if test -z "$1"; then
    exec grep -nH "$pat" `ls *.c *.cpp *.h *.s *.pl *.py *.tex *.css *.org *.m *.scm *.lisp *.lsp *.el *.java *.tcl *.txt *.fp *.f 2>/dev/null`
else
    exec grep -nH "$pat" "$@"
fi
