#!/usr/bin/tclsh
#
# indent/unindent
#
# usage: ind [COLUMNS [TEXT]]

set c 4
set prefix ""

if {$argc > 0} {
    set c [lindex $argv 0]

    if {$argc > 1} {
        set prefix [lindex $argv 1]
    }
}

if {[regexp {unind$} $argv0]} {
    set c [expr -$c]
}

if {$c > 0} {
    append prefix [string repeat " " [expr $c - [string length $prefix]]]
}

while {[gets stdin line] >= 0} {
    if {$line == "" && [eof stdin]} break

    if {$c > 0} {
        puts "$prefix$line"
    } else {
        puts [string range $line [expr -$c] end]
    }
}


# TODO
#
# - tabs are not expanded, yet
