#!/usr/bin/env tclsh
#
# line-wise replace

fconfigure stdout -translation lf
fconfigure stderr -translation lf
set opts {-all}
set rx {}
set subst {}

proc Usage {{code 1}} {
  puts stderr {usage: LR [-h] [-1] REGEXP [SUBST]}
  exit $code 
}

for {set i 0} {$i < $argc} {incr i} {
    set arg [lindex $argv $i]

    switch -regexp -- $arg {
        {^--?h(elp)?$} {Usage 0}
        {^-1$} {set opts {}}
        default {
            if {$rx == ""} {
                set rx $arg
            } elseif {$subst != ""} {
                Usage
            } else {
                set subst $arg
            }
        }
    }
}

while {[gets stdin line] >= 0} {
  puts [regsub {*}$opts -- $rx $line $subst]
}

