#!/usr/bin/env tclsh
#
# output selected snippet via dmenu(1) or output unicode codepoint


# Modify as appropriate
set snippetfile $env(HERE)/lib/snippets.tcl
set menufont "-misc-fixed-bold-r-normal--18-120-100-100-c-90-iso8859-1"

set snippets {}

source $snippetfile

set names {}

foreach s $snippets {
    append names "\n" [lindex $s 0]
}

if {[string length $names] > 0} {
    if {![catch {exec dmenu -b -fn $menufont -nf yellow -nb brown -sb white -sf orange << $names} result]} {
        foreach s $snippets {
            if {$result == [lindex $s 0]} {
                puts [lindex $s 1]
                exit
            }
        }

        catch {
            set c [format "%c" [scan $result "%x"]]
            puts $c
        }
    }
}
